# default ablation
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 12 --views 2 --mincrop_ratio 0.6 --mix_method wrmix
# rotation center
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 12 --views 2 --mincrop_ratio 0.6 --random_pos --mix_method wrmix
# random crop ratio
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 12 --views 2 --crop_ratio 0.8 --mix_method wrmix
# cropped into a circle
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 12 --views 2 --mincrop_ratio 0.6 --crop_mode 1 --mix_method wrmix
# background removal
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 12 --views 2 --mincrop_ratio 0.6 --remove_background --mix_method wrmix
# the number of rotation classes
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 4 --views 2 --mincrop_ratio 0.6 --mix_method wrmix &&
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 6 --views 2 --mincrop_ratio 0.6 --mix_method wrmix &&
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 8 --views 2 --mincrop_ratio 0.6 --mix_method wrmix &&
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 10 --views 2 --mincrop_ratio 0.6 --mix_method wrmix &&
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 18 --views 2 --mincrop_ratio 0.6 --mix_method wrmix &&
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 20 --views 2 --mincrop_ratio 0.6 --mix_method wrmix &&
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 30 --views 2 --mincrop_ratio 0.6 --mix_method wrmix &&
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 36 --views 2 --mincrop_ratio 0.6 --mix_method wrmix &&
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 40 --views 2 --mincrop_ratio 0.6 --mix_method wrmix &&
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 60 --views 2 --mincrop_ratio 0.6 --mix_method wrmix &&
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 72 --views 2 --mincrop_ratio 0.6 --mix_method wrmix &&
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 120 --views 2 --mincrop_ratio 0.6 --mix_method wrmix &&
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 180 --views 2 --mincrop_ratio 0.6 --mix_method wrmix &&
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 360 --views 2 --mincrop_ratio 0.6 --mix_method wrmix &&
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 3 --views 2 --mincrop_ratio 0.6 --mix_method wrmix &&
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 5 --views 2 --mincrop_ratio 0.6 --mix_method wrmix &&
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 9 --views 2 --mincrop_ratio 0.6 --mix_method wrmix &&
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 45 --views 2 --mincrop_ratio 0.6 --mix_method wrmix
# the number of feeding images
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 200 --save_point 150 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 12 --views 1 --mincrop_ratio 0.6 --mix_method wrmix &&
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 50 --save_point 30 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 12 --views 4 --mincrop_ratio 0.6 --mix_method wrmix &&
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 34 --save_point 25 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 12 --views 6 --mincrop_ratio 0.6 --mix_method wrmix &&
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 17 --save_point 15 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 12 --views 12 --mincrop_ratio 0.6 --mix_method wrmix
# data mixture methods
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 30 --views 2 --mincrop_ratio 0.6 &&
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 30 --views 2 --mincrop_ratio 0.6 --mix_method mixup &&
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 30 --views 2 --mincrop_ratio 0.6 --mix_method cutmix &&
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 30 --views 2 --mincrop_ratio 0.6 --mix_method hmix &&
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 30 --views 2 --mincrop_ratio 0.6 --mix_method gmix
# beta distribution alpha
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 12 --views 2 --mincrop_ratio 0.6 --mix_method wrmix --mix_alpha 0.5 &&
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 12 --views 2 --mincrop_ratio 0.6 --mix_method wrmix --mix_alpha 2
# intra-image vs. inter-image mixture kappa
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 12 --views 2 --mincrop_ratio 0.6 --mix_method wrmix --mix_kappa 0.5 &&
CUDA_VISIBLE_DEVICES=0 python main.py --task classification --gpus 0 --setname STL10_unlabelled --num_workers 8 --epochs 100 --save_point 80 --batch_size 1024 --lr 2e-4 --model_name resnet50 --optim adam --sup_method rotation --batch_shuffle --num_classes 12 --views 2 --mincrop_ratio 0.6 --mix_method wrmix --mix_kappa 0
